databases:
  - name: codebotdb
    plan: free
    databaseName: codebot
    user: codebot

services:
  - type: web
    plan: free
    name: codebot
    runtime: python
    pythonVersion: 3.11.9
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn codegen.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: codebotdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
